name: clickup_exporter

x-develop-config: &default-develop
  build: .
  platform: linux/amd64
  env_file:
    - .env
  volumes:
    - ./apps:/app/apps
    - python_env:/app/.venv
  develop:
    watch:
      - action: rebuild
        path: ./pyproject.toml
      - action: rebuild
        path: ./uv.lock
      - action: restart
        path: ./.env

services:
  backend:
    <<: *default-develop
    command: [ "sh", "-c", "exec uv run --no-default-groups --directory ./apps uvicorn core.asgi:application --reload --host 0.0.0.0 --port ${DJANGO_PORT}" ]

  lint:
    <<: *default-develop
    command: [ "sh", "-c", "exec uv run --no-dev --group lint --directory ./apps ruff check" ]
    profiles:
      - lint

  scheduler:
    <<: *default-develop
    command: [ "sh", "-c", "exec uv run --no-group lint --directory ./apps watchfiles --filter python 'uv run celery -A core beat -l info'" ]

  worker:
    <<: *default-develop
    command: [ "sh", "-c", "exec uv run --no-group lint --directory ./apps watchfiles --filter python 'uv run celery -A core worker --loglevel=info --concurrency=1'" ]

  flower:
    <<: *default-develop
    command: [ "sh", "-c", "exec uv run --no-group lint --directory ./apps watchfiles --filter python 'uv run celery -A core flower --persistent=True --db=\"flower_db\" --basic-auth=\"${FLOWER_USERNAME}:${FLOWER_PASSWORD}\"'" ]

volumes:
  python_env:
