name: deploy.yml
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION_NAME: ap-southeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ env.AWS_REGION_NAME }}
          role-to-assume: ${{ secrets.CI_ROLE }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}

      - name: Deploy on EC2 via SSM
        if: success()
        env:
          IMAGE_URL: ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}
        run: |
          echo "Deploying $IMAGE_URL to EC2 via SSM..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=clickup-exporter" \
            --parameters commands=["bash -lc 'export DOCKER_IMAGE_URL=${IMAGE_URL} && cd /home/ec2-user/app && docker compose -f docker-compose.prod.yml pull && docker compose -f docker-compose.prod.yml up -d'"] \
            --comment "GitHub Actions deploy: ${IMAGE_URL}" \
            --region ${{ env.AWS_REGION_NAME }}
